### ISSUE TITLE
Ability for Console Operators to customize branding

### ISSUE THREAD

**Issue by jdgemm** [helium/console#1172]
Console operators should have a simple way to customize their instance of Console branding. 

This includes ability to:
- swap out images/logos, UI and emails
- update welcome screen content
- change footer links

**Comment by vicmgs** [comment]
To customize your open source console:

1. Copy app-config.json into config folder
`cp templates/app-config.json config/app-config.json`

2. Customize config/app-config.json as needed

3. Switch to building your own console instead of using the quay image
`cp templates/docker-compose-server.yaml docker-compose.yaml`
